nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-4.1.0.cjs
logFilters:
  # This is likely related to this issue
  - text: "The lockfile would have been modified by this install, which is explicitly forbidden."
    level: "discard"
