version: "3.3"

services:
  jqh:
    build: 
      context: . 
      dockerfile: ./jobs_queue_handler/Dockerfile
    ports:
      - "5000:5000"
    image: jobs_queue_handler
    environment:
      - JQH_API_KEY_FILE=/secrets/jqh_api_key.secret
      - FLASK_APP=jobs_queue_handler

  flow_manager:
    build: 
      context: .
      dockerfile: ./flow_manager/Dockerfile
    ports:
      - "3000:3000"
    image: flow_manager
    environment: 
      - JQH_API_KEY_FILE=/secrets/jqh_api_key.secret
      - JQH_ADDRESS=http://jqh:5000
      - FM_API_KEY_FILE=/secrets/fm_api_key.secret
      - MONGO_ADDRESS=mongodb://mongo:27017/stalker
      - FM_JWT_SECRET_FILE=/secrets/fm_jwt_secret.secret
      - FM_REFRESH_SECRET_FILE=/secrets/fm_refresh_secret.secret
    links:
      - "jqh:jobsqueuehandler"
      - "mongo:db"
    volumes: 
      - ./flow_manager/src/:/fm/src/

  mongo: 
    build: ./database/
    ports: 
      - "27017:27017"
    logging:
      driver: none

  jobs_handler: 
    build: 
      context: .
      dockerfile: ./jobs_handler/Dockerfile
    image: jobs_handler
    environment:
      - JQH_API_KEY_FILE=/secrets/jqh_api_key.secret
      - FM_API_KEY_FILE=/secrets/fm_api_key.secret
    links: 
      - "jqh:jobsqueuehandler"
      - "flow_manager:fm"
    volumes: 
      - ./jobs_handler/src/:/jh/src/
  