FROM mcr.microsoft.com/dotnet/sdk:6.0
WORKDIR /app

EXPOSE 5135
EXPOSE 7135

# Always restart on rude edit
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1

RUN dotnet dev-certs https -t

COPY . .
RUN dotnet restore "./Orchestrator.sln"

CMD ["dotnet", "watch", "--project", "Orchestrator", "--no-hot-reload"]