FROM mcr.microsoft.com/dotnet/sdk:7.0
WORKDIR /app

EXPOSE 5135
EXPOSE 7135

# Always restart on rude edit
ENV DOTNET_WATCH_RESTART_ON_RUDE_EDIT=1

COPY ["Orchestrator.csproj", "."]
RUN dotnet restore "./Orchestrator.csproj"

RUN dotnet dev-certs https -t

COPY . .
CMD ["dotnet", "watch", "--no-hot-reload"]