apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: orchestrator-role
  namespace: stalker-jobs
rules:
  - apiGroups:
      - ""
      - "batch"
    resources:
      - "*"
    verbs:
      - "*"

# Actually needed
# - batch/create/jobs

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: orchestrator-service-account
  namespace: stalker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-service-account-role-binding
  namespace: stalker-jobs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: orchestrator-role
subjects:
  - kind: ServiceAccount
    name: orchestrator-service-account
    namespace: stalker
