FROM node:19.6.1-alpine

RUN apk update
RUN apk add bash
RUN apk add keybase-client --allow-untrusted --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/
RUN apk add g++ make py3-pip
RUN apk add git

RUN mkdir /fm; mkdir /secrets; mkdir /fm/src; mkdir /fm/test;
WORKDIR /fm/

ADD flow_manager/package.json .
ADD flow_manager/package-lock.json .

RUN npm install
RUN npm install keybase-bot

ADD flow_manager/nest-cli.json .
ADD flow_manager/tsconfig.build.json .
ADD flow_manager/tsconfig.json .

ENV KEYBASE_ALLOW_ROOT=1
RUN keybase ctl init

CMD ["npm", "run-script", "test:e2e:watch"]
EXPOSE 3000
