FROM node:16.10.0-alpine

WORKDIR /app

RUN apk update
RUN apk add bash
RUN apk add keybase-client --allow-untrusted --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing/

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . . 

CMD ["npm", "run", "start:debug"]
