FROM node:19.6.1-alpine

WORKDIR /app

RUN apk update
RUN apk add bash
RUN apk add g++ make py3-pip

COPY package.json package.json
COPY package-lock.json package-lock.json

RUN npm ci

COPY . .
RUN mkdir -p /certs/
COPY ca.pem /certs/
COPY client-signed.crt /certs/
COPY client.key /certs/

CMD ["npm", "run", "start"]
