FROM projectdiscovery/nuclei:v3.2.9

ENV PYTHONUNBUFFERED=1
RUN mkdir -p /nuclei/template && mkdir -p /nuclei/output
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python -m ensurepip
WORKDIR /nuclei/

COPY stalker_job_sdk /usr/src/stalker_job_sdk
RUN python -m pip install -e /usr/src/stalker_job_sdk
RUN python -m pip install httpx[http2]
COPY ./nuclei/nuclei_finding.py .
COPY ./nuclei/nuclei_wrapper.py .

ENTRYPOINT [ "python", "nuclei_wrapper.py"]