FROM alpine:latest

RUN apk add bash

ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN apk --no-cache add curl
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip requests watchdog

RUN mkdir /jh
WORKDIR /jh

COPY src .


CMD [ "watchmedo", "auto-restart", "--recursive", "--pattern=*.py", "--directory=.", "python3", "./jobs_handler.py" ]