#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

if (git rev-parse -q --verify MERGE_HEAD > /dev/null)
then
  echo "[PRECOMMIT] MERGE_HEAD exists. Skipping toolchains."
  exit 0
fi

root=$(pwd)
echo "[PRECOMMIT] Using $root as root directory."

for project in "docs" "packages/frontend/stalker-app" "packages/backend/jobs-manager/service" "packages/backend/orchestrator/service"
do
    cd "$root/$project"
    if [ -f "./.husky/pre-commit" ]; then
        if [ `git status --porcelain` ]; then
            echo "[$project] Found changes. Running toolchain."
            . "./.husky/pre-commit"
        else
            echo "[$project] No changes found."
        fi
    else
        echo "[$project] No toolchain found."
    fi
    cd "$root"
done
