name: Cron Service

on:
  pull_request:
    paths:
      - .github/workflows/cron-service.yml
      - "packages/backend/cron/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install --frozen-lockfile

      - run: yarn workspace @red-kite/cron test:cicd

      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: ./packages/backend/cron/test/jest-output.json
