name: Frontend

on:
  pull_request:
    paths:
      - .github/workflows/frontend.yml
      - "stalker_ui/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # FIXME: When we get rid of flex-layout and update the color picker, then we can remove legacy peer-deps.
      - run: npm ci --legacy-peer-deps
        working-directory: stalker_ui

      - run: npm run test:cicd
        working-directory: stalker_ui

  prod-build:
    name: Production Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # FIXME: When we get rid of flex-layout and update the color picker, then we can remove legacy peer-deps.
      - run: npm ci --legacy-peer-deps
        working-directory: stalker_ui

      - run: npm run build --prod
        working-directory: stalker_ui
