name: Jobs Manager

on:
  pull_request:
    paths:
      - .github/workflows/jobs-manager.yml
      - "packages/backend/jobs-manager+/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install --immutable
        working-directory: .

      - run: yarn workspace @red-kite/jobs-manager test:cicd
        working-directory: .

      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: ./jobs-manager/test/jest-output.json

  build:
    name: Production Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: yarn install --immutable
        working-directory: .

      - run: yarn workspace @red-kite/jobs-manager build
