# This is a basic workflow to help you get started with Actions

name: Stalker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: E2E Tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup MiniKube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main
        with:
          kubectl-install: true

      - name: Create test configurations
        run: |-
          echo "version: v2beta1" >> devspace.dev.yaml
          echo "name: stalker-vars-dev" >> devspace.dev.yaml
          echo "" >> devspace.dev.yaml
          echo "vars:" >> devspace.dev.yaml
          echo "  FM_FEATURE_ORCHESTRATOR_ENABLED: true" >> devspace.dev.yaml

      - name: Create namespace
        run: kubectl create namespace stalker

      - name: Run tests
        run: devspace run-pipeline flow-manager-e2e -n stalker

      - name: Diagnosis
        if: always()
        run: |-
          kubectl get all
          kubectl -n stalker get all -o yaml
