# This is a basic workflow to help you get started with Actions

name: Flow Manager / Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 15

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup MiniKube
        id: minikube
        uses: medyagh/setup-minikube@master

      - name: Install DevSpace
        uses: loft-sh/setup-devspace@main
        with:
          kubectl-install: true

      - name: Create namespace
        run: kubectl create namespace stalker

      - name: Run tests
        run: devspace run-pipeline flow-manager-e2e -n stalker

      - name: Update the results in the pull request
        uses: tanmen/jest-reporter@v1
        if: always()
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-file: ./flow_manager/test/jest-output.json
