name: Orchestrator

on:
  pull_request:
    paths:
      - .github/workflows/orchestrator.yml
      - "packages/backend/orchestrator/service/**"

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK 8.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "8.0.x"
          include-prerelease: true

      - name: Build
        working-directory: packages/backend/orchestrator/service/Orchestrator
        run: |-
          dotnet restore
          dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: packages/backend/orchestrator/service/Orchestrator.Tests
        run: |-
          dotnet restore
          dotnet test
